### ISSUE TITLE
segfaults on 64-bit windows?

### ISSUE THREAD

**Issue by echu** [embotech/ecos#112]
Following the discussion in #109, we should investigate issues related to JuliaOpt/ECOS.jl#16 on 64-bit Windows. If possible, we should set up an AppVeyor test for the ECOS library itself.

This is possibly due the the branch-and-bound module we added in the last release. One thought I had was to break out the branch-and-bound extension to a totally different repository. ECOS_BB essentially calls ECOS n times under the hood, so it really should be a standalone thing.

Additionally, we should consider setting up Travis to run downstream tests from CVXPY and JuMP and Convex.jl

cc @adomahidi @hanwang @tkelman @IainNZ @madeleineudell @SteveDiamond

**Comment by echu** [comment]
In the process of testing the ecos-python module, I believe we have fixed this issue.

@tkelman, can you confirm or deny? The fix should be introduced in the newest v2.0.0 tag. Note that it added exponential cone support, so it's backwards incompatible.

**Comment by tkelman** [comment]
32 bit windows (build via `CC='i686-w64-mingw32-gcc -g -Wl,--stack,8388608' AR=i686-w64-mingw32-ar make -e test shared` in cygwin) still doesn't converge on `lp_agg` at 665367009f9350cfa092f72f1ce58aa4e4514054: https://gist.github.com/tkelman/49b5c8ab6049690d5379

**Comment by tkelman** [comment]
and 64 bit (same build line but replacing `i686` with `x86_64`) still segfaults:
```
$ gdb -q ./ecostester
Reading symbols from ./ecostester...done.
(gdb) r
Starting program: /home/Tony/github/ecos/ecostester
[New Thread 7608.0x2118]

Program received signal SIGSEGV, Segmentation fault.
max_cols (E=E@entry=0x2c09c0, mat=0x2c0960) at src/equil.c:49
49              E[i] = MAX(fabs(mat->pr[j]), E[i]);
(gdb) bt
#0  max_cols (E=E@entry=0x2c09c0, mat=0x2c0960) at src/equil.c:49
#1  0x000000000040b3ac in use_ruiz_equilibration (w=0x234770) at src/equil.c:238
#2  0x000000000040b825 in set_equilibration (w=<optimized out>) at src/equil.c:340
#3  0x0000000000409f6d in ECOS_setup (n=1569, m=3120, p=0, l=1300, ncones=520,
    q=q@entry=0x594e80 <MPC01_q>, nexc=nexc@entry=0, Gpr=Gpr@entry=0x59b840 <MPC01_Gpr>,
    Gjc=Gjc@entry=0x734940 <MPC01_Gjc>, Gir=Gir@entry=0x6ac380 <MPC01_Gir>, Apr=0x0, Ajc=0x0,
    Air=0x0, c=c@entry=0x736200 <MPC01_c>, h=h@entry=0x5956c0 <MPC01_h>, b=0x0)
    at src/preproc.c:795
#4  0x0000000000410a6f in test_MPC01 () at test/MPC/MPC01.h:29
#5  all_tests () at test/ecostester.c:59
#6  main () at test/ecostester.c:93
```

**Comment by tkelman** [comment]
You're still running out of iterations on `lp_agg` on 32 bit and segfaulting on 64 bit, please reopen. Making data types depend on which compiler you're using isn't the right fix for 64 bit either.

```
$ gdb -q ./ecostester.exe
Reading symbols from ./ecostester.exe...done.
(gdb) r
Starting program: /home/Tony/github/ecos/ecostester.exe
[New Thread 2492.0x2500]

Program received signal SIGSEGV, Segmentation fault.
max_cols (E=E@entry=0x2f0a00, mat=0x2f09a0) at src/equil.c:49
49              E[i] = MAX(fabs(mat->pr[j]), E[i]);
(gdb) bt
#0  max_cols (E=E@entry=0x2f0a00, mat=0x2f09a0) at src/equil.c:49
#1  0x000000000040b3ac in use_ruiz_equilibration (w=0x3747a0) at src/equil.c:238
#2  0x000000000040b825 in set_equilibration (w=<optimized out>) at src/equil.c:340
#3  0x0000000000409f6d in ECOS_setup (n=1569, m=3120, p=0, l=1300, ncones=520,
    q=q@entry=0x594e80 <MPC01_q>, nexc=nexc@entry=0, Gpr=Gpr@entry=0x59b840 <MPC01_Gpr>,
    Gjc=Gjc@entry=0x734940 <MPC01_Gjc>, Gir=Gir@entry=0x6ac380 <MPC01_Gir>, Apr=0x0, Ajc=0x0,
    Air=0x0, c=c@entry=0x736200 <MPC01_c>, h=h@entry=0x5956c0 <MPC01_h>, b=0x0)
    at src/preproc.c:795
#4  0x0000000000410a6f in test_MPC01 () at test/MPC/MPC01.h:29
#5  all_tests () at test/ecostester.c:59
#6  main () at test/ecostester.c:93
```

**Comment by tkelman** [comment]
Apologies, I was on the wrong branch. There's no segfault now and 32 bit passes, but the 64 bit compiler-dependent data types is still not the right fix IMO.
